#
# arch/l4/mm/Makefile
#


obj-y	:= fault.o extable.o init.o ioremap.o pageattr.o pgtable.o mmap.o

extable-y	+= ../../../i386/mm/extable.o
mmap-y		+= ../../../i386/mm/mmap.o
pageattr-y	+= ../../../i386/mm/pageattr.o
pgtable-y	+= ../../../i386/mm/pgtable.o
