#
# arch/l4/mm/Makefile
#


obj-y	:= fault.o extable_32.o init.o ioremap.o pageattr_32.o pgtable_32.o mmap_32.o

extable_32-y	+= ../../../x86/mm/extable_32.o
mmap_32-y	+= ../../../x86/mm/mmap_32.o
pageattr_32-y	+= ../../../x86/mm/pageattr_32.o
pgtable_32-y	+= ../../../x86/mm/pgtable_32.o
