#
# arch/l4/mm/Makefile
#


obj-y	:= fault.o extable.o init.o ioremap.o pageattr.o pgtable_32.o mmap.o

extable-y	+= ../../../x86/mm/extable.o
mmap-y		+= ../../../x86/mm/mmap.o
pageattr-y	+= ../../../x86/mm/pageattr.o
pgtable_32-y	+= ../../../x86/mm/pgtable_32.o
