
lib-y	+= csumpartialcopyuser.o

lib-y	+= ../../../arm/lib/memcpy.o
lib-y	+= ../../../arm/lib/memmove.o
lib-y	+= ../../../arm/lib/memzero.o
lib-y	+= ../../../arm/lib/memchr.o
lib-y	+= ../../../arm/lib/strrchr.o
lib-y	+= ../../../arm/lib/copy_page.o
lib-y	+= ../../../arm/lib/lib1funcs.o
lib-y	+= ../../../arm/lib/muldi3.o
lib-y	+= ../../../arm/lib/div64.o
lib-y	+= ../../../arm/lib/ucmpdi2.o
lib-y	+= ../../../arm/lib/ashldi3.o
lib-y	+= ../../../arm/lib/ashrdi3.o
lib-y	+= ../../../arm/lib/lshrdi3.o
lib-y	+= ../../../arm/lib/testsetbit.o
lib-y	+= ../../../arm/lib/testclearbit.o
lib-y	+= ../../../arm/lib/setbit.o
lib-y	+= ../../../arm/lib/clearbit.o
lib-y	+= ../../../arm/lib/findbit.o
lib-y	+= ../../../arm/lib/changebit.o
lib-y	+= ../../../arm/lib/delay.o
lib-y	+= ../../../arm/lib/csumpartial.o
lib-y	+= ../../../arm/lib/csumpartialcopy.o
lib-y	+= ../../../arm/lib/io-readsl.o
lib-y	+= ../../../arm/lib/io-writesl.o
lib-y	+= ../../../arm/lib/backtrace.o

lib-y	+= ../pte.o
lib-y	+= ../memcpy_user.o
lib-y	+= ../uaccess.o
lib-y	+= ../proc.o
