
lib-y		:= io.o

obj-y		+= memcpy.o memzero.o lib1funcs.o muldi3.o div64.o \
		   memmove.o ucmpdi2.o \
		   testsetbit.o ashldi3.o testclearbit.o ashrdi3.o \
		   findbit.o testsetbit.o setbit.o clearbit.o \
		   memchr.o copy_page.o delay.o changebit.o \
		   csumpartial.o csumpartialcopy.o \
		   csumpartialcopyuser.o strrchr.o \
		   pte.o lshrdi3.o memcpy_user.o uaccess.o proc.o \
		   io-readsl.o io-writesl.o backtrace.o

memcpy-y		:= ../../../arm/lib/memcpy.o
memmove-y		:= ../../../arm/lib/memmove.o
memzero-y		:= ../../../arm/lib/memzero.o
memchr-y		:= ../../../arm/lib/memchr.o
strrchr-y		:= ../../../arm/lib/strrchr.o
copy_page-y		:= ../../../arm/lib/copy_page.o
lib1funcs-y		:= ../../../arm/lib/lib1funcs.o
muldi3-y		:= ../../../arm/lib/muldi3.o
div64-y			:= ../../../arm/lib/div64.o
ucmpdi2-y		:= ../../../arm/lib/ucmpdi2.o
ashldi3-y		:= ../../../arm/lib/ashldi3.o
ashrdi3-y		:= ../../../arm/lib/ashrdi3.o
lshrdi3-y		:= ../../../arm/lib/lshrdi3.o
testsetbit-y		:= ../../../arm/lib/testsetbit.o
testclearbit-y		:= ../../../arm/lib/testclearbit.o
testsetbit-y		:= ../../../arm/lib/testsetbit.o
setbit-y		:= ../../../arm/lib/setbit.o
clearbit-y		:= ../../../arm/lib/clearbit.o
findbit-y		:= ../../../arm/lib/findbit.o
changebit-y		:= ../../../arm/lib/changebit.o
delay-y			:= ../../../arm/lib/delay.o
csumpartial-y		:= ../../../arm/lib/csumpartial.o
csumpartialcopy-y	:= ../../../arm/lib/csumpartialcopy.o
io-readsl-y		:= ../../../arm/lib/io-readsl.o
io-writesl-y		:= ../../../arm/lib/io-writesl.o
backtrace-y		:= ../../../arm/lib/backtrace.o

pte-y			:= ../pte.o
memcpy_user-y		:= ../memcpy_user.o
uaccess-y		:= ../uaccess.o
proc-y			:= ../proc.o
