#ifndef __ASM_L4__API_L4ENV__CONFIG_H__
#define __ASM_L4__API_L4ENV__CONFIG_H__

/* L4 task number limits */
#define TASK_NO_MAX			255

/* must be 4mb aligned */
#define L4LX_USER_END_ADDRESS		(0xBFC00000UL)
#define L4LX_USER_KERN_AREA_START	L4LX_USER_END_ADDRESS
#define L4LX_USER_KERN_AREA_END		(0xC0000000UL)

#define UPAGE_USER_ADDRESS		(L4LX_USER_END_ADDRESS + 0x8000)
#define UPAGE_USER_ADDRESS_END		(UPAGE_USER_ADDRESS + PAGE_SIZE)

#define PAGE0_PAGE_ADDRESS		0x2000

#endif /* ! __ASM_L4__API_L4ENV__CONFIG_H__ */
